import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import chalk from 'chalk';
import { filterValidProjects, sortProjectsById } from '@/helpers';
import { CATEGORY_LABEL, LANGUAGES, WEBSITE_PROVIDER_LABEL } from '@/shared';
import type { Category, Language, Project } from '@/shared';
import data from '../../data/LIST.json';

const FILE_MAP: Record<Language, string> = {
  'en-US': 'LIST.md',
  'zh-CN': 'LIST.zh-CN.md',
};

const LINE_BREAK = '\n';

function createLink(href: string, text: string) {
  return `[${text}](${href})`;
}

function createBanner() {
  const BANNER = `<!--
  DO NOT EDIT THIS FILE DIRECTLY
  Generated by scripts/generate.ts
-->
`;
  return BANNER;
}

function createHeading(title: string, level: number = 2) {
  const hashtag = Math.max(Math.min(level, 1), 6);
  return String.prototype.concat(`${'#'.repeat(hashtag)} ${title}`, LINE_BREAK);
}

function generateProject(project: Project, lang: Language) {
  const blocks: Array<string> = [];

  const name = project.repository
    ? createLink(project.repository, project.name)
    : project.name;

  if (project.website) {
    for (const { url, provider } of project.website) {
      blocks.push(createLink(url, WEBSITE_PROVIDER_LABEL[provider][lang]));
    }
  }

  const description = project.description[lang];
  blocks.push(description);

  return [`- ${name}`, ...blocks.map((b) => `  - ${b}`), LINE_BREAK].join(LINE_BREAK);
}

export function prepare(projects: Array<Project>): Record<Category, Array<Project>> {
  const groupedProjects = filterValidProjects(projects).reduce(
    (acc, project) => {
      const category = project.category;
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(project);
      return acc;
    },
    {} as Record<Category, Array<Project>>
  );

  const sortedProjectGroups = {} as Record<Category, Array<Project>>;
  for (const [category, projects] of Object.entries(groupedProjects)) {
    sortedProjectGroups[category as Category] = sortProjectsById(projects);
  }

  return sortedProjectGroups;
}

function generate(lang: Language) {
  let doc = createBanner();
  doc += LINE_BREAK;

  const projectGroups = prepare(data as Array<Project>);
  for (const [category, projects] of Object.entries(projectGroups)) {
    doc += createHeading(CATEGORY_LABEL[category as Category][lang]);
    doc += LINE_BREAK;

    projects.forEach((project) => {
      doc += generateProject(project, lang);
    });
  }

  const outputDir = resolve(process.cwd(), `../`);
  const outputFile = resolve(outputDir, FILE_MAP[lang]);

  writeFileSync(outputFile, doc, 'utf-8');

  console.log(chalk.green(`Successfully generated ${FILE_MAP[lang]}`));
}

LANGUAGES.forEach(generate);
